site_name: Tunelio
site_description: Lightweight ngrok alternative - expose local servers via FastAPI + WebSockets
repo_url: https://github.com/Farhodoff/tunnel

theme:
  name: material

nav:
  - Home: index.md
  - API: api.md
  - Deploy: deploy.md

markdown_extensions:
  - tables
  - fenced_code
